name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    name: Тестування та лінтинг
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    
    steps:
    - name: Завантаження коду
      uses: actions/checkout@v4
    
    - name: Налаштування Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Встановлення залежностей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Лінтинг з flake8
      run: |
        flake8 app.py --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 app.py --count --max-complexity=10 --max-line-length=120 --statistics
    
    - name: Перевірка форматування з Black
      run: |
        black --check app.py test_app.py
    
    - name: Аналіз коду з Pylint
      run: |
        pylint app.py --disable=C0103,C0114,C0115,C0116 || true
    
    - name: Запуск unit тестів
      run: |
        pytest test_app.py -v --cov=app --cov-report=xml --cov-report=html
    
    - name: Завантаження звіту покриття
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report-${{ matrix.python-version }}
        path: htmlcov/
        retention-days: 7
    
    - name: Відправка покриття до Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        flags: unittests
        name: codecov-${{ matrix.python-version }}

  build:
    name: Збірка Docker образу
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Завантаження коду
      uses: actions/checkout@v4
    
    - name: Налаштування Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Побудова Docker образу
      run: |
        docker build -t task-manager:${{ github.sha }} .
        docker tag task-manager:${{ github.sha }} task-manager:latest
    
    - name: Збереження Docker образу
      run: |
        docker save task-manager:latest | gzip > task-manager.tar.gz
    
    - name: Завантаження артефакту
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: task-manager.tar.gz
        retention-days: 7

  security-scan:
    name: Сканування безпеки
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Завантаження коду
      uses: actions/checkout@v4
    
    - name: Запуск Trivy для сканування вразливостей
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Завантаження результатів до GitHub Security
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

  deploy:
    name: Розгортання
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Завантаження коду
      uses: actions/checkout@v4
    
    - name: Симуляція розгортання
      run: |
        echo "🚀 Розгортання додатку..."
        echo "📦 Версія: ${{ github.sha }}"
        echo "✅ Додаток успішно розгорнуто!"
